//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoboDesk.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoboDesk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap android_3 {
            get {
                object obj = ResourceManager.GetObject("android_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow {
            get {
                object obj = ResourceManager.GetObject("arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADAUGA.
        /// </summary>
        internal static string BTN_ADD {
            get {
                return ResourceManager.GetString("BTN_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;.
        /// </summary>
        internal static string BTN_ADD_PROD {
            get {
                return ResourceManager.GetString("BTN_ADD_PROD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alergeni.
        /// </summary>
        internal static string BTN_ALERGENS {
            get {
                return ResourceManager.GetString("BTN_ALERGENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuleaza.
        /// </summary>
        internal static string BTN_CANCEL {
            get {
                return ResourceManager.GetString("BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorii.
        /// </summary>
        internal static string BTN_CATEGORIES {
            get {
                return ResourceManager.GetString("BTN_CATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STERGE.
        /// </summary>
        internal static string BTN_DELETE {
            get {
                return ResourceManager.GetString("BTN_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODIFICA.
        /// </summary>
        internal static string BTN_EDIT {
            get {
                return ResourceManager.GetString("BTN_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logare.
        /// </summary>
        internal static string BTN_LOGIN {
            get {
                return ResourceManager.GetString("BTN_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meniuri.
        /// </summary>
        internal static string BTN_MENUS {
            get {
                return ResourceManager.GetString("BTN_MENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produse.
        /// </summary>
        internal static string BTN_PRODUCTS {
            get {
                return ResourceManager.GetString("BTN_PRODUCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;.
        /// </summary>
        internal static string BTN_REMOVE_PROD {
            get {
                return ResourceManager.GetString("BTN_REMOVE_PROD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALVEAZA.
        /// </summary>
        internal static string BTN_SAVE {
            get {
                return ResourceManager.GetString("BTN_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setari.
        /// </summary>
        internal static string BTN_SETTINGS {
            get {
                return ResourceManager.GetString("BTN_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mese.
        /// </summary>
        internal static string BTN_TABLES {
            get {
                return ResourceManager.GetString("BTN_TABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorii.
        /// </summary>
        internal static string CategoriesFrm {
            get {
                return ResourceManager.GetString("CategoriesFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteaza item....
        /// </summary>
        internal static string CB_DEFAULT_SELECT {
            get {
                return ResourceManager.GetString("CB_DEFAULT_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CB_ENABLED {
            get {
                return ResourceManager.GetString("CB_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alergeni.
        /// </summary>
        internal static string DGV_ALERGENS {
            get {
                return ResourceManager.GetString("DGV_ALERGENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cod.
        /// </summary>
        internal static string DGV_CODE {
            get {
                return ResourceManager.GetString("DGV_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string DGV_DISCOUNT {
            get {
                return ResourceManager.GetString("DGV_DISCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cod Familie.
        /// </summary>
        internal static string DGV_FAMILYCODE {
            get {
                return ResourceManager.GetString("DGV_FAMILYCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nume.
        /// </summary>
        internal static string DGV_NAME {
            get {
                return ResourceManager.GetString("DGV_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pret.
        /// </summary>
        internal static string DGV_PRICE {
            get {
                return ResourceManager.GetString("DGV_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Masa.
        /// </summary>
        internal static string DGV_TOKEN {
            get {
                return ResourceManager.GetString("DGV_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap en {
            get {
                object obj = ResourceManager.GetObject("en", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numele utilizator si/sau parola sunt incorecte!.
        /// </summary>
        internal static string ERR_LOGIN_FAILED {
            get {
                return ResourceManager.GetString("ERR_LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O eroare neprevazuta a aparut ! Cod eroare {1}.
        /// </summary>
        internal static string ERR_UNKNOWN {
            get {
                return ResourceManager.GetString("ERR_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alergeni.
        /// </summary>
        internal static string LBL_ALERGENS {
            get {
                return ResourceManager.GetString("LBL_ALERGENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cod.
        /// </summary>
        internal static string LBL_CATEGORYCODE {
            get {
                return ResourceManager.GetString("LBL_CATEGORYCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nume categorie.
        /// </summary>
        internal static string LBL_CATEGORYNAME {
            get {
                return ResourceManager.GetString("LBL_CATEGORYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cod.
        /// </summary>
        internal static string LBL_CODE {
            get {
                return ResourceManager.GetString("LBL_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriere.
        /// </summary>
        internal static string LBL_DESCRIPTION {
            get {
                return ResourceManager.GetString("LBL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string LBL_DISCOUNT {
            get {
                return ResourceManager.GetString("LBL_DISCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval Discount.
        /// </summary>
        internal static string LBL_DISCOUNTINTERVAL {
            get {
                return ResourceManager.GetString("LBL_DISCOUNTINTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activat.
        /// </summary>
        internal static string LBL_ENABLED {
            get {
                return ResourceManager.GetString("LBL_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produse Existente.
        /// </summary>
        internal static string LBL_EXISTING_PRODUCTS {
            get {
                return ResourceManager.GetString("LBL_EXISTING_PRODUCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familie.
        /// </summary>
        internal static string LBL_FAMILY {
            get {
                return ResourceManager.GetString("LBL_FAMILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produse Meniu.
        /// </summary>
        internal static string LBL_MENU_PRODUCTS {
            get {
                return ResourceManager.GetString("LBL_MENU_PRODUCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nume.
        /// </summary>
        internal static string LBL_NAME {
            get {
                return ResourceManager.GetString("LBL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola.
        /// </summary>
        internal static string LBL_PASS {
            get {
                return ResourceManager.GetString("LBL_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pret.
        /// </summary>
        internal static string LBL_PRICE {
            get {
                return ResourceManager.GetString("LBL_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizator.
        /// </summary>
        internal static string LBL_USER {
            get {
                return ResourceManager.GetString("LBL_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoboDesk.
        /// </summary>
        internal static string LoginFrm {
            get {
                return ResourceManager.GetString("LoginFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoboDesk.
        /// </summary>
        internal static string MainFrm {
            get {
                return ResourceManager.GetString("MainFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produse.
        /// </summary>
        internal static string ProductsFrm {
            get {
                return ResourceManager.GetString("ProductsFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ro {
            get {
                object obj = ResourceManager.GetObject("ro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mese.
        /// </summary>
        internal static string TablesFrm {
            get {
                return ResourceManager.GetString("TablesFrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti parola.
        /// </summary>
        internal static string TB_PASS {
            get {
                return ResourceManager.GetString("TB_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cauta....
        /// </summary>
        internal static string TB_SEARCH {
            get {
                return ResourceManager.GetString("TB_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduceti nume utilizator.
        /// </summary>
        internal static string TB_USER {
            get {
                return ResourceManager.GetString("TB_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunteti sigur ca vreti sa stergeti aceasta inregistrare?.
        /// </summary>
        internal static string WAR_DELETE {
            get {
                return ResourceManager.GetString("WAR_DELETE", resourceCulture);
            }
        }
    }
}
